baseURL = "https://dadafterforty.be"
languageCode = "en-us"
title = "d(e)adafterforty"
disableKinds = ["taxonomyTerm"]
description = "what is dad may never die"
summaryLength = 30
Copyright = "d(e)adafterforty 2019"

[params]
    Description = "what is dad may never die"
    Title = "d(e)adafterforty"
    TwitterAuthor = "@dadafterforty"
    TwitterCreator = "@dadafterforty"
    logo = "/images/logo.png"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/jandedobbeleer"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://facebook.com/dadafterforty"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/dadafterforty"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/dadafterforty"
     [params.colors]
        background = "#111"
        foreground = "#fff"
        hover = "#111"
        link = "#3b6e80"

[Author]
    name = "d(e)adafterforty"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
