[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = "vibrate 'self'; sync-xhr 'self'; microphone 'none'; camera 'none'"
    Expect-CT = "max-age=0, report-uri='https://dadafterforty.report-uri.com/r/d/ct/reportOnly'"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src 'self' platform.twitter.com cdn.syndication.twimg.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com use.fontawesome.com cdn.jsdelivr.net platform.twitter.com; img-src 'self' data: *.twitter.com pbs.twimg.com; frame-src *.twitter.com; font-src 'self' cdn.jsdelivr.net use.fontawesome.com fonts.gstatic.com; report-uri https://dadafterforty.report-uri.com/r/d/csp/enforce"
    X-Content-Security-Policy = "default-src 'none'; script-src 'self' platform.twitter.com cdn.syndication.twimg.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com use.fontawesome.com cdn.jsdelivr.net platform.twitter.com; img-src 'self' data: *.twitter.com pbs.twimg.com; frame-src *.twitter.com; font-src 'self' cdn.jsdelivr.net use.fontawesome.com fonts.gstatic.com; report-uri https://dadafterforty.report-uri.com/r/d/csp/enforce"
    X-WebKit-CSP = "default-src 'none'; script-src 'self' platform.twitter.com cdn.syndication.twimg.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com use.fontawesome.com cdn.jsdelivr.net platform.twitter.com; img-src 'self' data: *.twitter.com pbs.twimg.com; frame-src *.twitter.com; font-src 'self' cdn.jsdelivr.net use.fontawesome.com fonts.gstatic.com; report-uri https://dadafterforty.report-uri.com/r/d/csp/enforce"
    X-Welcome-Stanger = "Hi there, welcome to d(e)adafterforty, make sure to follow me!"
    X-GitHub-Location = "https://github.com/jandedobbeleer"
    X-Keybase-Location = "https://keybase.io/jandedobbeleer"
    X-Twitter-Location = "https://twitter.com/dadafterforty"
    X-Facebook-Location = "https://www.facebook.com/deadafterforty"
    X-Instagram-Location = "https://instagram.com/dadafterforty"
